import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "Public",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gray-100 min-h-screen">

          {/* Header / Navigation */}
          <header className="bg-white shadow fixed top-0 left-0 right-0 z-50 ">
            <div className="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center">
              <h1 className="text-3xl font-bold text-blue-900">
                <Link href="/">ALINO Nzungu</Link>
              </h1>              
              
              <nav className="space-x-4">
                <Link href="/new" className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded">
                  Ajouter un post
                </Link>
              </nav>
            </div>
          </header>

          {children}

        </div>
      </body>
    </html>
  );
}
